#include "sacn_config_common.h"

#define SACN_DYNAMIC_MEM 1

#define SACN_RECEIVER_MAX_UNIVERSES            0
#define SACN_RECEIVER_MAX_SOURCES_PER_UNIVERSE 0
#define SACN_RECEIVER_TOTAL_MAX_SOURCES        0
#define SACN_DMX_MERGER_MAX_MERGERS            1
#define SACN_DMX_MERGER_MAX_SOURCES_PER_MERGER 1
