#include "sacn_config_common.h"

#define SACN_DYNAMIC_MEM 0

#define SACN_RECEIVER_MAX_UNIVERSES            30
#define SACN_RECEIVER_MAX_SOURCES_PER_UNIVERSE 8
#define SACN_RECEIVER_MAX_SUBS_PER_SOCKET      5
#define SACN_MAX_NETINTS                       100

#define SACN_SOURCE_MAX_SOURCES              10
#define SACN_SOURCE_MAX_UNIVERSES_PER_SOURCE 2048

#define SACN_SOURCE_DETECTOR_MAX_SOURCES              2
#define SACN_SOURCE_DETECTOR_MAX_UNIVERSES_PER_SOURCE 700

#define SACN_DMX_MERGER_MAX_SLOTS 500
