#include "sacn_config_common.h"

#define SACN_DYNAMIC_MEM 1

#define SACN_DMX_MERGER_MAX_SLOTS 500

#define SACN_DMX_MERGER_DISABLE_INTERNAL_PAP_BUFFER   1
#define SACN_DMX_MERGER_DISABLE_INTERNAL_OWNER_BUFFER 1
