if(SACN_BUILD_TESTS)
  set(ETCPAL_BUILD_MOCK_LIB ON CACHE BOOL "Build the EtcPal mock library" FORCE)
endif()

if(COMPILING_AS_OSS)
  if(SACN_OFFLINE_DEPENDENCIES_PATH)
    add_oss_dependency(EtcPal SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH}/etcpal)

    if(SACN_BUILD_TESTS)
      add_oss_dependency(googletest SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH}/googletest)
      add_oss_dependency(GSL SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH}/gsl)
    endif()
  else()
    get_cpm()

    add_oss_dependency(EtcPal GIT_REPOSITORY https://github.com/ETCLabs/EtcPal.git)

    if(SACN_BUILD_TESTS)
      add_oss_dependency(googletest GIT_REPOSITORY https://github.com/google/googletest.git)
      add_oss_dependency(GSL GIT_REPOSITORY https://github.com/microsoft/gsl.git)
    endif()
  endif()
else()
  include(${CMAKE_TOOLS_MODULES}/DependencyManagement.cmake)
  
  if(SACN_OFFLINE_DEPENDENCIES_PATH)
      add_project_dependencies(SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH})

    if(SACN_BUILD_TESTS)
      add_project_dependency(googletest SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH}/googletest)
      add_project_dependency(GSL SOURCE_DIR ${SACN_OFFLINE_DEPENDENCIES_PATH}/gsl)
    endif()
  else()
    add_project_dependencies(SOURCE_DIR ${SACN_EXTERNAL})

    if(SACN_BUILD_TESTS)
      add_project_dependency(googletest SOURCE_DIR ${SACN_EXTERNAL}/googletest)
      add_project_dependency(GSL SOURCE_DIR ${SACN_EXTERNAL}/gsl)
    endif()
  endif()
endif()

if(TARGET EtcPalMock)
  set_target_properties(EtcPalMock PROPERTIES FOLDER dependencies)
endif()
